### ISSUE TITLE
I wizzy working?

### ISSUE THREAD

**Issue by vonpupp** [kamon-io/docker-grafana-graphite#113]
Hi,

I am trying to run this as follows:
```
docker-compose up

kamon-grafana-dashboard | 2017-10-08 22:08:42,337 INFO success: graphite-webapp entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
kamon-grafana-dashboard | 2017-10-08 22:08:42,337 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
kamon-grafana-dashboard | 2017-10-08 22:08:42,337 INFO success: carbon-cache entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
kamon-grafana-dashboard | 2017-10-08 22:08:56,036 INFO exited: export-datasources-and-dashboards (exit status 1; not expected)
kamon-grafana-dashboard | 2017-10-08 22:08:57,038 INFO spawned: 'export-datasources-and-dashboards' with pid 102
kamon-grafana-dashboard | 2017-10-08 22:08:58,039 INFO success: export-datasources-and-dashboards entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
kamon-grafana-dashboard | 2017-10-08 22:09:11,835 INFO exited: export-datasources-and-dashboards (exit status 1; not expected)
kamon-grafana-dashboard | 2017-10-08 22:09:12,009 INFO spawned: 'export-datasources-and-dashboards' with pid 164
kamon-grafana-dashboard | 2017-10-08 22:09:13,054 INFO success: export-datasources-and-dashboards entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
kamon-grafana-dashboard | 2017-10-08 22:09:26,826 INFO exited: export-datasources-and-dashboards (exit status 1; not expected)
kamon-grafana-dashboard | 2017-10-08 22:09:27,842 INFO spawned: 'export-datasources-and-dashboards' with pid 226
kamon-grafana-dashboard | 2017-10-08 22:09:28,843 INFO success: export-datasources-and-dashboards entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

Since it is `export-datasources-and-dashboards ` that seems to fail, I open up the script and saw a wizzy call. So I shell into the container and executed manually wizzy with the following result:

```
root@e31eae250bb1:/# wizzy
/usr/lib/node_modules/wizzy/src/index.js:16
	commands.help();
	         ^

TypeError: commands.help is not a function
    at Object.<anonymous> (/usr/lib/node_modules/wizzy/src/index.js:16:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

Any idea, please?

Thanks a lot.

**Comment by jreinert** [comment]
Having the same issue here. Prevents me from saving dashboards or alerts.

**Comment by jotadepicas** [comment]
+1

**Comment by mduft** [comment]
Seeing the same crash:

grafana_1  | 2018-01-29 07:41:43,275 INFO exited: export-datasources-and-dashboards (exit status 1; not expected)
grafana_1  | 2018-01-29 07:41:43,796 INFO spawned: 'export-datasources-and-dashboards' with pid 617
grafana_1  | 2018-01-29 07:41:44,835 INFO success: export-datasources-and-dashboards entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

However it does not seem to keep me from using anything. I can create and save dashboards just fine. My "only" problem with this is the log cluttering so far :D

**Comment by wflanagan** [comment]
Is there a workaround for this?
