### ISSUE TITLE
Disk Usage

### ISSUE THREAD

**Issue by outrunthewolf** [kamon-io/docker-grafana-graphite#24]
I'm getting the following error after running for a few days:

```sh
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 84, in emit
    self.flush()
  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 64, in flush
    self.stream.flush()
IOError: [Errno 28] No space left on device
```

My HDD is around 500GB and only around 13GB is being used, so... I'm not sure why it says its running out of space. Any ideas?

**Comment by ivantopo** [comment]
While investigating the comments on #16, I found [this post] stating that the default disk allowance for docker containers is 10GB, that might be the issue you have. I couldn't find any official docker documentation that would confirm that statement nor did I try to reach the limit myself, but it seems to be real. 

I guess your options are either to start the container with `--storage-opt dm.basesize=manyG` or mount the whisper storage folders outside the container, I'm not sure if any limits apply on the second case though. 

Also, could you please take a look at the container file system to ensure that the logs are not eating up disk space and that your disk allowance is mostly consumed by whisper files? the whisper files are located at `/opt/graphite/storage/whisper/`.


[this post]: https://goldmann.pl/blog/2014/09/11/resource-management-in-docker/#_limiting_disk_space

**Comment by outrunthewolf** [comment]
Genius. I thought it could be a docker issue but couldn't find the exact post. I'll check that out now and get back to you. Thanks for the quick response.

**Comment by edanshalom** [comment]
Also had the same issue, I fixed it in the following way:
https://jpetazzo.github.io/2014/01/29/docker-device-mapper-resize/
